### ISSUE TITLE
"Grösse Ändern" can be misleading

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#139]
Currently the button to change the subscription type(s) is labeled "Grösse Ändern". However depending on the types that are set up, the user may rather look for "Change Content" (Products) "Change Price" or "Change Contribution" (Assignments/Shares).

A better name may be "Change Composition" ("Zusammensetzung ändern").

Any suggestions?

**Comment by PaulKC** [comment]
I would not like a change to "Change Composition". If you use the custom subscription addon, which lets the user select the composition for his/her subscription individually, this would lead to a lot of confusion.

**Comment by motu55** [comment]
actually there is a text next to the button which could contain some explanation, so it would not be enough to change the button.
but then again we will not find a generic text which suits all. so instead of going through a boring discussion about terminology we do the followin instead we pack each row in here
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/templates/subscription_change.html
into a snippet and iclude them, which makes it possible to easily change single rows without having to overload the whole template
