### ISSUE TITLE
Bad redirect after login

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#172]
Django setting `LOGIN_REDIRECT_URL = "/my/home"` needs to be set in `settings.py`. Should be added to documentation and instructions.

**Comment by motu55** [comment]
Actually most instances solve this problem like this:
https://github.com/juntagrico/juntagrico-science-django-cookiecutter/blob/28bd33aa68d909b244b9a802ff1786c8097dc10b/%7B%7Bcookiecutter.code%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/urls.py#L22
as we do this for all our instances we set up in the paas and since people which host their juntagrico themselves should be able to handle this problems themselves i see no need to add this to the documentation
