### ISSUE TITLE
Improve user password reset process

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#174]
The current user password reset works as follows:

1. User browses to "forgot password" page and enters mail address
2. System generates new password and sends to user via mail
3. User has to browse to login page and copy+paste password from mail
4. User has to manually browser to "change password" after login with new password

The password reset process might be more clear with the following setup: (example on https://simpleisbetterthancomplex.com/tutorial/2016/09/19/how-to-create-password-reset-view.html):
1. User browses to "forgot password" page and enters mail address
2. User receives mail with link to password reset page with time-limited token
3. On password reset page, user enters and confirms new password and then proceeds to login with new password

**Comment by motu55** [comment]
Django already provides such a process
see here
https://docs.djangoproject.com/en/3.0/topics/auth/default/#django.contrib.auth.views.PasswordResetView
it has to be checked if we can overwrite the field where the email is taken from or if we can use parts of it.
also it would be nice to have a similar mechanism for new registrations

**Comment by wknds** [comment]
please assign that one to me, if still open.

**Comment by wknds** [comment]
Btw. as a feature suggestion: i saw on republik.ch that they use a password-less sign-in system where you receive an email with a link to finalize the sign-in process. Would that be something for this application?

**Comment by motu55** [comment]
paswordless sign in is definetely out of the scope for this issue. so it would be a specific featurerequest.
this would require some investigation, since we use juntagrico also as an oauth provider and if that is feasible or not.
personally i am no big fan of the republic paswordless login, i found it very anoying and tedious. 
but if you implements this feature witch a good otp we can reuse this for a passwordlesslogin once the feature request arises

**Comment by wknds** [comment]
I implemented the password reset by using the django framework. The first prototype has been committed to the branch [reset_password_process_v2](https://github.com/juntagrico/juntagrico/tree/reset_password_process_v2)

**Comment by pascalfree** [comment]
Hi wknds
Thanks for your contribution.
I merged the newest master into your branch, because it was quite behind, please pull the newest version.
Also please open a pull request (even when not finished yet), that will make it easier to review and give feedback. You can do that here: https://github.com/juntagrico/juntagrico/compare/master...reset_password_process_v2

Overall it looks good and I think you can continue in this direction.
Here some points that I saw so far I think should be addressed:
- [ ]  The email form should use the bootstrap theme (the input field looks different than all others now)
- [ ] path names should use `-` instead of `_`
- [ ] Override template for new password form

On your questions:
- The config server URL is the right place to take the the main url from
- The settings tell it, that the templates are in that folder. Specifically in `testsettings.py` in `TEMPLATES` `OPTIONS` `loaders` the `app_directories.Loader` will look for the this template folder as [documented here](https://docs.djangoproject.com/en/3.0/ref/templates/api/#django.template.loaders.app_directories.Loader).
- `{{}}` takes a [variable](https://docs.djangoproject.com/en/3.0/ref/templates/language/#variables) and prints its value to the output, while `{%%}` executes a [template tag](https://docs.djangoproject.com/en/3.0/ref/templates/language/#tags) (special function definitions for the template). Some [built-in template tags](https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#ref-templates-builtins-tags) exist that allow to create for loops and if conditions and much in the template.

**Comment by nixnuex** [comment]
The main issue here seems to be that jungagrico seems to have diverged from Django's User Model in the sense that we neither use their default email field nor implement an adapted custom User Model. So we cannot just use the built-in functionality by just adapting the templates.

Either we manage somehow to upgrade to a custom User Model or we have to re-implement our own PasswordResetForm.

First seems to be hard/impossible for production systems, so we go the second path?

**Comment by motu55** [comment]
i think we either propagate the email into the corresponding user object or just use the one from the user
i do not know why we don't do that is a legacy from the ortoloco code.

**Comment by nixnuex** [comment]
I would agree to move the email completely to the User model to make use of Django's built-in features.

Should we open a new issue for this or just start a separate pull request on this effort?

**Comment by wknds** [comment]
Should I continue to work on this or is someone going to take over?

**Comment by pascalfree** [comment]
A new pull request is enough I'd say and I also agree on moving the email completely to the user and make a property on the member that forwards it.

@wknds if you like you can continue on this issue. Let us now if you won't continue, so somebody can take over.

**Comment by motu55** [comment]
for traceability a new issue would be beneficial
@wknds i added this to the 1.2.5 milestone please let me know if you cannot finish it for that release

**Comment by wknds** [comment]
@pascalfree @motu55 please take over 👍
