### ISSUE TITLE
Zusätzliche Export-Möglichkeit: Die Abos (Name, Teilpartner, Abo-Typ, Depot, Zusatzabos)

### ISSUE THREAD

**Issue by jolling-eg** [juntagrico/juntagrico#182]

**Comment by motu55** [comment]
check if possible with the xlsx exporter we have for entities.
if not do it similar to the mebers export

**Comment by motu55** [comment]
also put all export related views in an separate view called views_export.py

**Comment by pascalfree** [comment]
Here is our implementation that covers some of the columns you mentioned and could be adapted:
https://github.com/mehalsgmues/juntagrico-mag/blob/6423507776d9a2f27ba6ff7435de222c4d5a0439/mehalsgmues/views.py#L233
As we have only one subscription size with different prices the list shows the subscription prices rather than their name.
