### ISSUE TITLE
Include juntagrico extensions into test set

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#206]
There is a risk that juntagrico extensions running live somewhere break because of changes in the juntagrico code base (e.g. juntagrico-billing). How can we include checks/tests of the extensions against the current master branch to protect them from breaking?

**Comment by motu55** [comment]
this problem occurs only in instances which have the dev version of juntagrico installed.
usually a new version of juntagrico also requires that the extension adapt their requirements.txt and pip would take care if there are conflicting juntagrico versions.
Since this affects only a few instances it would be overkill to device a whole build pipeline for that

**Comment by PaulKC** [comment]
As a maintainer of an extension I often had the problem that modules were moved or renamed in juntagrico. It would be nice to document such bigger refactorings. This would make it much easier to adopt the extensions.

**Comment by motu55** [comment]
usually if tey are big refactorings we would add the to the release notes, otherwise alle the changes can be tracked ba checking whcih commits were added between two release tags
