### ISSUE TITLE
Improved exports > jobs overview

### ISSUE THREAD

**Issue by flurin-conradin** [juntagrico/juntagrico#219]
This is a feature request raised by Basimilch for a better overview of the members assignments status. 
They would like to have the following columns in the current report:

- Assignments required (Anzahl nötige Einsätze)
- Assignments completed (Anzahl geleistete Einsätze)
- Assignments planned (Anzahl geplante Einsätze)
- Assignments to be done (Anzahl offene Einsätze)

If you think this is useful, you can assign this issue to me.

**Comment by motu55** [comment]
is this in the export or in the members filter?

**Comment by flurin-conradin** [comment]
This would be in exports > job overview ("Mitglieder mit Arbeitseinsätze und Tätigketsbereichen"). 
The exact place does not matter though. It's more the feature that is important for the administrators to gain an overview  of the points above. 
Any other way to achieve this would be great.

**Comment by motu55** [comment]
ok
in the subscription filter something like this ais already implemented just subscription wise
the idea why this is in the subscription is because there we see how many assignments are required
otherwise we would have either to use the total per member or split them and that is probably always wrong (do you get what i am saying or am i to cryptic?)
so check out the feature in the subscription filter and let me know if that would be sufficient or not

**Comment by flurin-conradin** [comment]
Sorry I took some time.

Yes, your explanation makes sense. 

I spoke to the team at Basimilch.
They would be fine with the implementation of this in the subscription filter. However, what is missing for them is Assignments planned (Anzahl geplante Einsätze). THEY would like to have this info, because when sending reminders for members to sign up for jobs, they would not want to send a reminder to someone who has already signed up for a job.

Do you think this would be a useful feature?

**Comment by motu55** [comment]
I packed this request in an new issue here with more context and a broader rework of the filter lists #256
