### ISSUE TITLE
Make user ID field in Member non-nullable

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#270]
Currently, the Member to User ID field is allowed to be NULL. A NULL entry can result in malfunction (password reset, ...). Shouldn't we enforce the OneToOne link with non-nullable?

**Comment by motu55** [comment]
you are right this should be not nullable, but i could be because of this it is
https://github.com/juntagrico/juntagrico/blob/bee4ac8bae77457a523e56d226fd249619641116/juntagrico/entity/member.py#L111
since this is called after the member has been saved.
so this has to be adressed as well

**Comment by motu55** [comment]
I merged the pullrequest. What i think might be stell missing here is some kind of atomic transaction constraint when generating a member because if the member creation faiils later on the created user is still there which leads to dangling users which will not break the system at the moment but once we move the email adress to the user this will become a problem

**Comment by motu55** [comment]
i did not find a quick way to get tit in to a transaction so that it is atomic for all the possible ways to create a member so i close that for now and if we see a lot of dangling users in the future we circle back to it
