### ISSUE TITLE
User menu entries not visible

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#274]
User menu entries not visible / disappeared. Same for admin menu entries.

**Comment by samuel-iseli** [comment]
I'm having a similar problem. Getting error ("list is not hashable*) from `{% include admin_menus %}` in `admin_menu.html`.
Could this be caused by #255?
If I revert `admin_menu.html` and `user_menu.html` to using `{% for menu in admin_menus %}`  loop with `{% include menu %}` the menus show correctly again.
@motu55 could you have a look at it? I don't understand why the `{% include admin_menus %}` would work as `admin_menus` seems to be a list of menu templates.

**Comment by nixnuex** [comment]
@samuel-iseli You have to pull the newest version of Django through requirements.txt to at least get it working. Still, menus are missing.

**Comment by samuel-iseli** [comment]
The `{% include ... %}` template tag doesn't really support lists. It doesn't crash anymore when given a list with django 3.1, but the documentation says: "Additionally, the variable may be an iterable of template names, in which case the first that can be loaded will be used, as per select_template()" , see https://docs.djangoproject.com/en/3.1/ref/templates/builtins/ .

That's the reason why the addon menus stopped appearing. The first entry in `admin_menus` and `user_menus` are empty "custom" templates.

Should change these back to loop over `admin_menus` and `user_menus` then it works again.

**Comment by nixnuex** [comment]
"i reverted to commit which caused all this so this pullrequest is no longer required"

_Originally posted by @motu55 in https://github.com/juntagrico/juntagrico/pull/285#issuecomment-703553392_
