### ISSUE TITLE
re joining job should edit and not add assignments

### ISSUE THREAD

**Issue by motu55** [juntagrico/juntagrico#300]

**Comment by pascalfree** [comment]
I can confirm that in half of the cases when member want to unjoin a job they just accidentially registered with too many people and want to reduce that to 1.
However it has to be considered, that this change would mean, that reducing the assignments to 1 is possible while unjoining completely is not possible for the member.
This is probably fine, as it still prevents "bad weather cancellations" to some extent. But I think this should be discussed with the cooperatives.

**Comment by pascalfree** [comment]
The UX study suggested these changes to the job signup process (including my interpretation):
- Allow selecting one self and/or co-members on sign-up. also allow only signing up co-member. Ideally it is still traceable who did the actual signup.
  - At least one person of the sub (self or co-members) must be selected.
  - members without co-members should not see checkboxes but only: "Signing up as 'your name'."
- Display the number of people being signed up in the submit button: "Sign up X people".
- The method of adding more (non-members) to the job tested in the study seemed to complicated. I suggest a button "Bring another Person" instead of the "+" button that was tested. Maybe rather gray than green to make it less attractive. After clicking the button a number field may show "'X' other people", where X can be increased if X becomes 0 the button is shown again. Naming the other people is not necessary.
- Add a checkbox to confirm, that the member understood the conditions of the signup and what they would have to do if they want to cancel later on.
  - This will replace the popup.
  - after signing up the same information should be displayed as a info-box at that location.
  - The conditions are likely to need adjustment for some users.

Additions relevant to this issue:
- When signed up already the same form will be shown and selections and numbers can be changed and signup can be updated. Same conditions apply: At least one person must be selected.

**Comment by pascalfree** [comment]
The relevant aspects of this issue are solved by #631
