### ISSUE TITLE
Error when member cancels membership with subscription and unpaid share

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#313]
A member with subscription and unpaid share (e.g. a new member) will trigger a validation error if they try to cancel their membership via form.
The reason is this check:
https://github.com/juntagrico/juntagrico/blob/fee6477cc7f7d0559891ea44a979a813e7530f73/juntagrico/views.py#L437-L440
`is_cooperation_member` will return false, because the shares is not paid yet and thus `deactivation_date` is set. The subsequent consistency check will complain about the member still having an active subscription.

It should work if we check here if the member has any ordered and not paid back shares.
This however adds a backdoor to cancel unpaid shares, wich is not possible in the share management view. Not sure if that is an issue. I would rather allow more to the member and let the member admins handle the case from there.

**Comment by motu55** [comment]
since this is only annoying but does not lead to data inconsitency i put it into 1.2.5
also it seems we need some discussion here

**Comment by motu55** [comment]
prevent members with unpaid shares from cancelling their membership would do the trick, with a meaningfull message like 
"you have unpaid shares please sort this issue out with the administrators before you can cancel your membership"
the only issue remaining is what happens if the unpaid share is dleted in the admin menu this would also again trigger the exception with the active subscription maybe  we need a check for that as well
so in short mo checks

**Comment by pascalfree** [comment]
Fixed with 5d7094ae668ebcc48eea08c5faefa6e1772df1bc
