### ISSUE TITLE
Feature request: User export share certificate (pdf?)

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#350]
Some members may have significant amounts of shares. A download option in the share management section would allow the user to download a semi-official share certificate with address, amount and sum in currency.

**Comment by motu55** [comment]
I believe to remember, that we discussed this some time ago, and for legal reasons we did not implement that. Please talk to Tex since he is the expert concerning shares and legal reasons.

Also what would be the benefit of this?

**Comment by nixnuex** [comment]
The reason was mentioned to be a more "official" appearance of a certification about some kCHF of shares, maybe also for tax declaration reasons.

I will check back and report here.

**Comment by nixnuex** [comment]
Feedback: members should have access to a kind of annual share certificate. Ideally automatically generated and archived as PDFs but I would consider this as too much overhead for juntagrico.

Proposal: members get access to annual certificates for last years with actives shares dated 31.12. or today's active shares for the running year. These will be generated on request as html or pdf and not saved on server side. The info is anyways available in the DB.

**Comment by motu55** [comment]
storing makes no sense since it is a huge amount of space not really needed since we kan generate the information for any point in time.
from my personal tax experience a such certification is not needed (even if you get auditet). So it would be nice to have a professional opinion of an tax expert and also some an example how it should look would be helpfull. so that if it is tax relevant the correct information is on the certificate (other wise members could just write one themselves usinf open office ;))

**Comment by nixnuex** [comment]
Format should just contain organization name, address, date 31.12.xxxx, member and address and amount and total value of active shares on 31.12.
