### ISSUE TITLE
Notifications on subscription part creation and cancellation

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#369]
Admin notification email should be added.
Preferably grouped in a single email.
Also make sure to not send double notification emails if subscription creation or cancellations notification is already sent.

**Comment by motu55** [comment]
The permissions are already there since it is marked @notifiable

the mechanism used for shares and subscription will not work here for creation in the cases of subscription creation, since until now we used the post save signal where we have very limited context information
but then again for subscription cancelation we do not hook into the corresponding signal (why not?) so we can add the method to the corresponding view methods.

Programatically it would be interessting to just use the signals and a generic email template so that the @notifiable decorator would all be that is required, on the other hand will that lead to a lot of emails which are just spam. 

So from an admin point of view it would be nice to get only meaningfull emails, which means adding the calls into the view methods. This would also meant that changes made in the admin interface will not trigger an email.

whichever way we approach i would prefer that we use the same approach for all the notifications.

@pascalfree can you proviede an overview which notification we have so far uses a signal and whcih ones are called from a view method (and if there is a specific reason why this is so)

**Comment by pascalfree** [comment]
I agree that the form based notifications are better to control the frequency and content of the notification and to avoid sending out emails "as a side effect". If the notification on change via admin form is still needed it may be added to the admin form as well.
I would still create signals for all these notifications. Later on, instead of sending out the emails directly, a notification add-on may hook into the signals to collect them and e.g. send out daily summaries instead of individual emails like proposed for the job notifications #542.

**Comment by pascalfree** [comment]
Fixed by #410.
Additional scope is part of #528
