### ISSUE TITLE
Show "Abo-Typ" in "Abo"-overview

### ISSUE THREAD

**Issue by LouRB** [juntagrico/juntagrico#371]
We as Gemüsekooperative Rote Beete eG close to Leipzig / Germany want to use Juntagrico.

Our Abos have a kind of ID, which is built from a letter and two numbers, for example J13. The Abos have different prices and sizes, so we would want to use "Abo-Typ" as the ID oder Name for the individual "Abo". To work with Juntagrico it would be necessary to see the "Abo-Typ" in the "Abo"-Overview. Only in the list-exports wouldn't be enough. 

We started some stuff as Juntagrico-Docker here: https://github.com/Rote-Beete

**Comment by georgkrause** [comment]
This issue is about showing a needed information in the subscription list. Since each organization might face different needs, it seems to be the best for me to implement a "column picker" which enables the user (or admins?) to choose which information is shown.

I would like to work on this, so feedback from any maintainer would be welcome.
