### ISSUE TITLE
Let members manage multiple subscriptions

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#38]
Currently members have no options to manage multiple subscriptions of the same or different types. Organisations that allow multiple subscriptions have to do these changes manually in the admin interface. To let the member manage all their subscriptions the following needs to be modified:
1. Allow the selection of various combinations and amounts of subscriptions during signup
2. Allow changing the subscriptions individually.
    - Currently this is called "change size" but should be more like "change type"

Maybe a setting is helpful to enable or disable multiple subscriptions per member to keep the user interface simple if only 1 subscription is allowed per member.
A more sophisticated solution may include:
1. A limit per subscription type: How many of this subscription type can one member get? `0 = no limit`

**Comment by motu55** [comment]
Since we at ortoloco only have 1 or two subscription which contain more than one type for a total of 250 subscriptions, and it is not nescessary a bad thing if changes and requests for such special types are monitored, i would argue it is ok as it is. but we could use the new input used for shares which we will roll out with the december release also for subscription types. but i would put this on the backlog since it involves wuite an amount of checks especially if we implement trial subscriptions.
do you have many of these cases so that it is a pressing issue?

**Comment by pascalfree** [comment]
We have 12 member groups that have more than 1 subscription. It is not urgent, just a feature that is missing yet.

**Comment by motu55** [comment]
the radio buttons here
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/templates/size_change.html
and here
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/templates/createsubscription/select_subscription.html
could be replaced with the numeric input fields used here
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/templates/createsubscription/select_shares.html#L47
of course the methods in the back would require adaptation
maybe we would need a setting in order to enable and disable this feature or use radio buttons during ignup and the numeric stuff during size change.
@pascalfree what do you think?

**Comment by pascalfree** [comment]
I would create a setting to enable/disable the feature in general, for organizations that don't allow accumulation of subs.

When enabled: To keep the registration simple for the 85% of people that just want 1 sub, I would keep the radio button view initially and add a button at the top and bottom (left of the "next" button) saying "Order multiple subscriptions" that then enables the numeric input fields.

Could be a setting in the URL of that page, that defines if radio buttons of numeric fields are shown.
Same during registration and size change.
In size change, the numeric field view should be loaded automatically if the member has > 1 sub already.
