### ISSUE TITLE
Enable and promote deployment as serverless function

### ISSUE THREAD

**Issue by Levino** [juntagrico/juntagrico#382]
I would like to have as little hassle when I set up a deployment of this great piece of software. So I would prefer to be able to deploy it as a serverless function. Vercel [supports python](https://vercel.com/docs/serverless-functions/supported-languages#python) for their serverless functions. Now I am a JS/TS coder so I do not know much about dep management of python but I guess the app should export some kind of top level function for the serverless function to call. Another question is how configuration of the app should be handled (does the app read it from the environment or do the configuration params have to be provided to the top level function explicitly? I vote for the latter).

In case someone is wondering: Docker is not an alternative for me and should not be for others: It is just too much setup work. I mean for it to work properly you would have to setup Kubernetes and that is way overkill for this. Vercel [phased out docker](https://vercel.com/support/articles/does-vercel-support-docker-deployments) when lambda functions came, netlify never provided deployment of docker containers. Serverless functions have won...

**Comment by motu55** [comment]
This is just a django app, so you would not deploy it on its own but in a django instance. How you deploy your django instance is absolutelly your business and does not at the least concern us. You could even say for us it's schnurzpiepegal.

**Comment by Levino** [comment]
Would it not be nice if more people used this? I did not even say that you have to do this. I might make a PR for it when I have the time. There are others creating docker images for this etc. It would make more sense if the support for these deployment functionalities would be shipped with your package. You could still use your package as you used to. If you do not want to address a wide range of users, why open source this in the first place?

**Comment by Levino** [comment]
And one has to change your code in order to deploy it via a serverless function, I guess. Or is it already possible easily following the docs of vercel? Can I import your package in my python project and then somehow generate a WSGI instance? (I really am no python coder, sorry).

**Comment by motu55** [comment]
I thought my last message was pretty simple to follow , but obviously i was wrong.
As i said this is a django app. This means:
**juntagrico will not run on it own**
It has to be deployed inside a **django instance**.
So this basically boils down to 

- if django can be deployed as a serverless function, then juntagrico can be deployed as a serverless function
-  if django cannot be deployed as a serverless function, the juntagrico cannot be deployed as a serverless function (and no amount of code in this project can change that)

To find out if django can be deployed as a serverless function please consult your favourite search engine.

The question of deployment as i said before is **out of scope** for this preoject.

We simply do not care how you deploy or configure your django instance, and therefore do not offer any advice or support or recomendation in that direction.

So for us this issue is closed so we will not consider any of this further.

**Comment by Levino** [comment]
Is there a guide on how I can use juntagrico in my django app? Or maybe an example django app using it?

**Comment by Levino** [comment]
I was able to get this [running](https://github.com/Levino/juntagrico-serverless/tree/fe82f707757773567e6dd5287c27a1e716673ab8). I gets deployed via vercel serverless functions and requires a (managed) postgresql database to be reachable from the internet. The configuration of the secrets happens via vercel environment variables, see the `settings.py` for details. However is interested is invited to create issues in my repo.
