### ISSUE TITLE
Security Improvements

### ISSUE THREAD

**Issue by patrickuhlmann** [juntagrico/juntagrico#408]
Hi

Do you have a template for the installation. I saw that most of the installations use the same (from a security standpoint) non-optimal settings. For example: https://github.com/puraverdura/juntagrico/blob/master/puraverdura/settings.py

The problems are:
* SECRET_KEY should be read from an environment variable
* DEBUG should be set to false
* TEMPLATES OPTIONS debug should not be set to true

Note: if you set DEBUG to false it will stop serving the static files out-of-the box. This can be easily fixed by adding middleware like whitenoise.middleware.WhiteNoiseMiddleware

I would like to contribute an improved template but I couldn't find it (respectively was unsure if it is the juntagrico-demo or the 
juntagrico-science-django-cookiecutter repository)

**Comment by motu55** [comment]
Hi
The template is as you suspected this repository
https://github.com/juntagrico/juntagrico-science-django-cookiecutter
Since it is higly intertwined with the 
https://github.com/juntagrico/juntagrico-paas
some code changes were nescessary there to change the template
- the secret key comes now per default from en an env variable
- debug while allways set through false due to the corresponding env variable in the paas will now also be false if the vriable is not set for some reasons

since debug was false per default also wehen a bi mistically obscured static files are served through nginx directly
see here for the used template
https://github.com/juntagrico/juntagrico-paas/blob/main/adminconsole/templates/env/domain.txt
