### ISSUE TITLE
View one date format for whole user interface.

### ISSUE THREAD

**Issue by gako-li** [juntagrico/juntagrico#420]
Show all dates in the same (short) format dd.mm.yyyy. For example, always 31.12.2021 instead of once 31 December 2021 and another time 31.12.2021.
Example view Administration / Share certificates / Paid on. This helps admins to copy/paste dates for searchings, inserts, replacements and comparments.

**Comment by motu55** [comment]
The problem here is more or less described here 
https://blog.mounirmesselmeni.de/2014/11/06/date-format-in-django-admin/
since it is not feasible to adapt all dates in our model admins and so far I have not found a way to programatically change the settings (any hints are welcome); I do not see a way to implement this.
you can of course adapt the setting yourself
