### ISSUE TITLE
Validate location link to map on job

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#421]
## Issue
If a location is given for a job a link to a google map search appears in the job description. It does not guarantee to give a meaningful result. If for example a common name for the location (that is known to the member) is given, many results show following the link and confuse new members.

## Suggestion
Create an entity to define a location (common name, address, possibly coordinates) that can then be selected in the job. 
Usually there is only a very limited number of a location where jobs take place.
The same entity might be used as well to store the depot location.

**Comment by motu55** [comment]
Don't we risk with that we get into a situation similar to the job types where we can get a list too large to filter since there are a lot of jobs which are only done once like onetime jobs? Also we cannot delete them since the job depends on them and therefore the assignments depend on them.
I see the problem but I think having the location info like coordinates in the job type itself. We also should discuss if we loose the link to google and use the same leaflet openstreetmap mechanism like for depots. but the we loose the benefit google maps gives us with the routing.
alternatively we could say use meaningfull locations and not inside descriptions, or split the location in a name and an address and only the address is used in the google link

**Comment by pascalfree** [comment]
There shouldn't be too many locations in most cases. And the more locations there are the more the need for a predefined list rises as nobody will want to remember all the addresses for these (or the coordinates).

I would argue that also one time jobs will often reuse existing locations.
To handle larger selections I suggest using [autocomplete_fields](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields). We might want to allow manual sorting of the locations to put the most common ones on top.
Finally old locations could be hidden like we did for the jobtypes.

leaflet sounds good. We could show a leaflet map (load on click, to limit usage of the osm servers) and in addition a link to open the routing on google maps.

And an additional reason to use the same entity for depot locations is, that, at least in our case, all depots are also a job location (of the "cleanup depot job").

**Comment by pascalfree** [comment]
We just got feedback from another surprised member regarding this issue.

I'll try to implement this on tuesday using entities as I described.
