### ISSUE TITLE
Required assignments logic for under-year subscriptions

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#442]
The required assignments logic for under-year subscription part starts is based on the subscription activation date and not on the part activation date. If someone has an active subscription and later wants to add another subscription part with required assignments, the latter is not weighted correctly.

On the rounding logic: Wouldn't make it more sense to ceil the fractional required assignments? This would reflect more the need for engagement through assignments. Currently, 0.49 required assignments results in 0/no need for contribution.

**Comment by pascalfree** [comment]
This issue came up again recently with trial subscriptions, where a new full subscription usually follows as a new part in the same year.

The calculation should be as follows:
reduce the required assignments for each part, based on their start/end date (if it starts and/or ends in the current business year). Then sum these required assignments and then round.
For subscriptions with trial period, the required assignments should be calculated proportional to the trial period, e.g. it should be assumed that the required assignments are due within this trial period.
