### ISSUE TITLE
Feature request: default activity areas

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#452]
During sub creation or sub join, users should be assigned to default activity areas defined by a flag in the entity. Later, they are free to change their activity areas.

**Comment by zesinho** [comment]
I created a draft PR #462, but i'm not sure if i understood the feature request correctly. 
My questions are:

- What do you mean by "defined by a flag in the entity"? Do you want to choose per `Subscription` model which `ActivityArea` is default and than add the member to this ActivityArea when the related 'Subscription' is created or joined? (this i how i created the draft PR)
- Should co-members also be added to the default activity area?

**Comment by nixnuex** [comment]
Hi @zesinfo
Thanks for looking into this! I just got confirmation that our use case got simpler: We want to add all members and co-members that start or join a subscription to be added to all core activity areas. We already have this flag ("core") on the ActivityArea, this would allow implementation without altering the model / without migration. Now my preferred way.
The more general solution would add a new boolean field like "AutoAddMembers" for the same use case.

The question is more how to handle the point in time: I guess, subscription activation (which basically sets the activation date) would be the right moment. As result, members would receive ActivityArea mails even before their actual subscription start but this seems to be the only well-defined point in the subscription lifecycle model. And for all additional co-members during active subscriptions. @motu55, what do you think?

**Comment by nixnuex** [comment]
P.S.: If we use the existing "core" flag, we would need a config parameter like "AutoAddCoreActivityAreas".

**Comment by pascalfree** [comment]
I would stick to the original option with the `auto_add_new_members` flag, because it is more likely to fit the use case of others, e.g. cooperatives that don't use the core flag.

Adding, when activation date is set is fine I'd say, The members also start recieving the general newsletter, before their subscription is activated (at least in our case).

As an extra we might want to show the area selection during the signup process, such that the member is already aware of the areas and the fact that they are automatically added to some. The auto-add-areas would be preselected on this page. Plus "you can change this later" message.

**Comment by zesinho** [comment]
Ok, i got it. I'll change my draft PR and let you know when its ready for review.

**Comment by nixnuex** [comment]
@zesinho Do you need help with this?

**Comment by zesinho** [comment]
@nixnuex i'm sorry, i couldn't find the time to work on it so far. I will schedule it for next weekend!

**Comment by zesinho** [comment]
pull request updated: https://github.com/juntagrico/juntagrico/pull/462

**Comment by nixnuex** [comment]
Thanks a lot for implementing this!

Seems to be merged in fc0950d
