### ISSUE TITLE
Calendar view of jobs

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#49]
Add option to show jobs in a calendar view.
Maybe even provide an ical for syncing with calendar software

**Comment by motu55** [comment]
do you mean all jobs or the jobs a user has subscribed for?

**Comment by pascalfree** [comment]
Good point. Both would be nice.
And maybe even filter by activity area and have an option to show all activity areas the member is following. This would also be a new feature for the list view.

Plus the confirmation email of the assignment could also include the event invitation.

**Comment by motu55** [comment]
there was an apporach to include an ical invitation in the email but it did not work properly so it was comented out i'll create a separate ticket for that since i think this would already be great and move this issue to the backlog for the moment since it requires a lot of specification and even some ux work

**Comment by pascalfree** [comment]
I started working on an calendar view using https://fullcalendar.io/

**Comment by pascalfree** [comment]
see unofficial extension: https://github.com/juntagrico/juntagrico/pull/132#issuecomment-605692618
