### ISSUE TITLE
Manage non-job events

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#52]
Currently jobs could be (mis)used to announce important events (with 0-value assignments) to people who don't read the organisation newsletter.

It would be nice to have the possibility to specifically create and display internal events that aren't jobs, but still lets the members sign up to it. This could be an extension.

**Comment by motu55** [comment]
interesting idea.
would these internal events be displayed alongside the jobs or in a separate list (i would advise against a separate list since it bloats up the whole thing)
the 0 value assignemt while possible at the moment still requires manual labour
i would rather implement a good 0 value solution than add another entity for that (maybe only a child instance to better filter for events) since it contains the same stuff.

**Comment by pascalfree** [comment]
Display could be in the same list. I think the list separation could be done by overwriting some templates if needed by some organisations. 
Maybe the title of the table is then misleading though.
0 value assignments (aka events) should be clearly labeled as such to avoid confusion. Should be CSS stylable.

I would ask for input of other juntagrico users on this feature.
