### ISSUE TITLE
Undefined template variable in when editing "recuring job"

### ISSUE THREAD

**Issue by robwa** [juntagrico/juntagrico#530]
When trying to edit a job in the admin (e.g. `/admin/juntagrico/recuringjob/1/change/`) there seems to be an undefined template variable:

```
NameError at /admin/juntagrico/recuringjob/1/change/
In template, undefined variable or unknown value for: 'inline_admin_form.fk_field.field'
```

I could track this error down to the `ContactInline` used in `juntagrico.admins.job_admins.JobAdmin`. If I remove the inline from the list of inlines, the error disappears.

Can you reproduce the error?

**Comment by pascalfree** [comment]
We had such an issue I think during development but then it disappeared.

Are you running locally in debug mode?

Did you do manage.py migrate?

Not sure what helps but it should run fine in production if it's the same issue.

**Comment by robwa** [comment]
It only happens if we check for non-existing template variables. As we probably shouldn't do this in production, we can close this issue.

**Comment by flurin-conradin** [comment]
I ran into the same issue. We had a setting to explicitly raise an error when a field in a template is undefined. It as caused by a setting in the TEMPLATES OPTIONS, i.e.`"string_if_invalid": InvalidTemplateVariable("%s"),` This is only thought for debug purposes as described [here](https://docs.djangoproject.com/en/4.0/ref/templates/api/#how-invalid-variables-are-handled).

If I change the line to "string_if_invalid": "UNDEFINED HERE", I can see that there is some undefined field in the admin interface. 

![image](https://user-images.githubusercontent.com/32741304/230838620-ef4dfca1-8201-4c48-b0ac-9eeaa098c099.png)

My solution for now is to remove the `string_if_invalid` setting from my template options.
