### ISSUE TITLE
Activity area presentation

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#75]
Currently the activity areas might be described in a document that is linked with the setting ACTIVITY_AREA_INFO.

Here I suggest a more flexible approach:

- The activity area could be presented with more details on a separate page. e.g. /area/id
- The description of the activity area should be editable by its coordinator.
  - Maybe additional coordinators/assistants can be specified, that have write access.
- A link might be specified per activity area that directs to further resources: e.g. a google drive folder, a whatsapp chat, etc.
  - Alternatively the description could contain clickable links.

**Comment by motu55** [comment]
ACTIVITY_AREA_INFO is an url so it does not need to be an document per se
for detailspage see
/my/teams/id/
given the right permissions an area coordinator can change its area the permissions are change area and is area admin
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/entity/jobs.py#L44

cklickable linkks could be done by marking the description as safe here
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/templates/team.html#L15
but i am not shure if this is clever since not it people would edit that therefore just posting urls would be safer.

**Comment by pascalfree** [comment]
Thanks for the feedback.
Here are my updated suggestions:

- The activity areas listed in `/my/participation` should be linked to the team page `/my/teams/<id>/`
- On the team page there should be a button to either join or leave the activity area
- The coordinator has access to edit the activity area, but does not see a link to the admin page
  - There could be an `edit` link visible to the coordinator (and admins) on the team page that leads directly to `/admin/juntagrico/activityarea/<id>/change/`
  - Should the coordinators be able to remove themselves as a coordinator? Currently possible, but messy, if they don't have access to the member list.
  - Should the coordinator be able to add or remove members of the activity area? Currently possible.
  - Currently the Coordinator can see all the information of the activity area members in the filter list: Number of assignments, subscriptions, other activity areas, phone numbers, emails, etc. Together with the ability to add any member to the activity area, any coordinator could get most member data. That might be more power than expected. What Information does the coordinator actually need?
- Links are currently not clickable in the description. Maybe the description should be [`urlized`](https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#urlize)?

**Comment by motu55** [comment]
i implemented most of it
the following was done
- urlize description
- added link in participation page
- now it is everywhere called area and not team anymore
- used ajax to subscribe and unsubscribe so there is no more save button
- can join an area on the area page
- coordinators cannot change the coordinator name and core setting in the admin page
- coordinators see the link to the admin area

for the other questions:
- coordinators should be abel to change the mebers otherwise they would always have to ask the info team
- coordinators should be able to add and remove persons from jobs otherwise also the info team would have to do this. therefore they need the can view members permission (pre django 2.1 or 2.2 they rewuired the meber change permission thats an improvement) so they can anyway see all the members.  what ecactly area admins need to see is probably a big discussion and one could argue in either direction. i would put that issue if it really is one into another ticket and if ok close this one and merge the improvements

**Comment by pascalfree** [comment]
Perfect.
I agree that we can close this issue and open another one when needed.
