### ISSUE TITLE
Add direct links to edit entry for admins

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#78]
Especially for jobs it can be hard to find a specific instance in the admin interface. A direct link on the front-end to edit that job, helps in many cases. The link would only be visible with the required privileges.
In some other cases such a link might be helpful as well.

I implemented a job edit link for our instance:
https://github.com/mehalsgmues/juntagrico-mag/commit/8f8d46eca2f94930f5487686abfddcd3183a992e#diff-4b421fa34336433072a819bcb25687d7R10
However I have to override the entire template to do so.
Instead of the template tag the `isRecuring` Flag could also be passed with the dictionary.

**Comment by motu55** [comment]
the following commit fixes discrepances in the job search
https://github.com/juntagrico/juntagrico/commit/95782dac5e4ddbb5cb6496fc20345b83b1e52841
unfortunatelly it works only in the following date format mm-dd-yyyy thats something worth investigating.
we should avoid inter app dependencies as much as possible since they require some additional maintenance.
Therefore the policy for the moment is that we improve the filtering in the admin interface - since thats where the problem actually lies - rather than implement a workaround (some would even say a hack)

**Comment by motu55** [comment]
after researching and rembereing i found the reverse function which does provide a way to an url for an entity in the admin interface. that way we get notified in the django relese notes if something changes.
also the check if we should provide a link to the job and which kind of job it is is now done completelly in python so that we are sure the right permission apply
