### ISSUE TITLE
Prevent deletion of job if members are assigned

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#80]
Currently a job can be deleted and no notification will be sent to the members that were assigned to it.

Desired behavior:
- Moderators with the given permissions should have the ability to delete jobs if no members are assigned. Mostly to delete accidientally created jobs themselves.
- When trying to delete a job that has members assigned to it, it should be canceled instead and not deleted.
- To delete the job anyways, the members must be unassigned first.
- Bonus: Past jobs could be deleted even with members assigned to it, if this does not affect their assignment count of this season, i.e. jobs from last season.

**Comment by motu55** [comment]
deletion should always delete and should also be silent.
so the only thing here relevant would be to adapt the follwing line
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/entity/jobs.py#L288
by changing from cascade to protect
since the user is informed, that he will be deleting assignments as well as the job i think this is not nescessay but would be open to the argument that is already protect on almost all other relations

in order to prevent the deletion of jobs who should be canceled instead remove the delete right from the moderators

the whole past jobs deletion is a sepratate issue we should tackle at some point in the near future

**Comment by motu55** [comment]
implemented according to proposed solution above
