### ISSUE TITLE
Assignment Requests

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#87]
Some members do work in the garden without registering for a job. Usually because there is no job published for that activity, as the members work self organized individually or in teams.
Currently there is no convenient way to add such assignments retroactively and it requires extra work by the member admins.
I propose this feature to simplify the process and lower the barrier to entry for members to get self organized.

I would give this feature low priority.
The feature could be added as a plugin and may look like this:

# In the main app
Jobs (and one time jobs) would get one additional field `hidden`, that would make the job visible only to the members that are assigned to it. In the frontend an icon would indicate, that a job is not visible to everyone, to avoid confusion.

# In the plugin
### SelfAssignableJobs
- linked to a job (or one time job) (one to one)
  - The job that is linked would be set to hidden by default.
- auto accept: requests are accepted without waiting for approval by admin

some nice to have fields:

- list of members that can approve self assignments on this job
- list of members that can request self assignments on this job
- list of activity areas whose members can request self assignments on this job
- start and end time on when self assignment is possible

### AssignmentRequest

- linked to an assignment (one to one)
  - assignment is created automatically and added to a job. The assignment multiplier is 0 initially and is set to the requested amount when the request is approved.
- request for date and time: Date and time when the job was done (if applicable)
- requested amount of assignments
- requested to (member with rights to approve request): Usually the person, that told the member that they should use this feature.
- request message: short description by member that requests the assignment (optional)
- status: awaiting approval / approved / automatically approved / denied

maybe:
- request response message: for response of approver (usually to explain why it was denied)

### Request Form
The form is accessible through a sub menu under the point "Assignments"

- selection of job to request assignment for (taken from SelfAssignableJobs)
- requested amount of assignments
- request for date and time (defaults to now)
- request to
- request message (optional)

### Show and revoke
In the list of past jobs the members can see their requested assignments with their status (approved/denied). They may also revoke their request here.

## Notification
The admin that is specified in request to, gets an email after the request  with a link to accept and a link to deny the request. Or at least a link to edit the request in the admin page.

**Comment by motu55** [comment]
This is highly overengineered and a bit overkill for the amount of possible memberes which apply for this sort of process
a lot of it can basically be achieved by a dummy job which is eiter on the last day of the business year or at the last day of the month
members can "request" assingments by subscribing to the job every time they did an assingment on the field so this replaces the form
also can an admin directly contact mebers from the job overview site so this goes for the notification if nescessary
with the link to the admin page from a job an admin get quickly to the assingments and can remove them
users can see if theri request has been aprooved after the job has "finished" and their assignment is still there
so with some ducktaping and using the stuff that is allready there most of the problem can be addressed
what is not adressed but also disputable is the option of hiding jobs and and managing who can see them. but this is actually also some admin overhead in order to a job everybody can see 
what is not adressed and could be usefull is the possibility of adding comments to assingments when a member subscribe to a job. this feature would probably be usefull in general and not only in this case
but this should go into another issue
I will close this issue for now. Should there be a huge rally from different cooperatives to implement this we can reopen it any time

**Comment by pascalfree** [comment]
An implementation very similar to the above description is now live at "meh als gmües":
https://github.com/mehalsgmues/juntagrico-mag/tree/master/juntagrico_proactive
It is implemented as a plugin basically ready to move to its own repo, after testing.
