### ISSUE TITLE
Menu Restructure

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#88]
The menu could be restructured and renamed like this (suggestion):

- Jobs
  - Your Jobs (future and past)
- Activity Areas (renamed from participation: first section with the two links should be removed from the activity area page)
- Subscription
- Share (new: should contain the part about shares that is now on the subscription page)
- Profile
- Contact

In addition the assignment overview in the menu should link to "Your Jobs"

**Comment by motu55** [comment]
omitted shares since they are actually only important on subscription creation and canceliing and if there are meber modifcations in the subscription. they are not an essential part of the everyday life that it calls for a new meu point
also shares belong to the context of the subscription same as the depot for example
but we could include the share part also in the profile since that would also be aplace a person would check if she has shares but this should be part of another issue
